// Generated by CoffeeScript 2.7.0
(function() {
  var Dark, element;

  Dark = function() {};

  element = document.body;

  if (onclick) {
    element.classList.toggle("toggleDarkMode");
    console.log('click!');
  }

}).call(this);
