// Generated by CoffeeScript 2.7.0
(function() {
  var borderBox, borderColor, borderRange, contentBox, contentColor, contentRange, paddingBox, paddingColor, paddingRange;

  borderRange = document.getElementById("border-range");

  paddingRange = document.getElementById("padding-range");

  contentRange = document.getElementById("content-range");

  borderColor = document.getElementById("border-color");

  paddingColor = document.getElementById("padding-color");

  contentColor = document.getElementById("content-color");

  borderBox = document.querySelector(".border");

  paddingBox = document.querySelector(".padding");

  contentBox = document.querySelector(".content");

  borderRange.addEventListener("change", function() {
    // console.log("border")
    return borderBox.getComputedStyle.padding = borderRange.value + "px";
  });

  paddingRange.addEventListener("change", function() {
    // console.log("padding")
    return paddingBox.getComputedStyle.padding = paddingRange.value + "px";
  });

  contentRange.addEventListener("change", function() {
    // console.log("content")
    return contentBox.getComputedStyle.padding = contentRange.value + "px";
  });

  borderColor.addEventListener("change", function() {
    // console.log("b color")
    return borderBox.getComputedStyle.backgroundColor = borderColor.value;
  });

  paddingColor.addEventListener("change", function() {
    // console.log("p color")
    return paddingBox.getComputedStyle.backgroundColor = paddingColor.value;
  });

  contentColor.addEventListener("change", function() {
    // console.log("c color")
    return contentBox.getComputedStyle.backgroundColor = contentColor.value;
  });

}).call(this);
