// Generated by CoffeeScript 2.7.0
(function() {
  var Dark, element;

  Dark = function() {
    console.log('click! Dark Function ran');
    return document.body.classList.toggle("toggleDarkMode");
  };

  element = document.getElementById("button-darkMode");

  if (element) {
    element.addEventListener("click", Dark);
  } else {
    console.log("Failed!");
  }

}).call(this);
