// Generated by CoffeeScript 2.7.0
(function() {
  // functions goes here
  var FullDate, addPrefix, addRawTextResult, addTextResult, clearDisplay, clearInput, form, global, global_prop, handleForm, scrollDown, time;

  handleForm = function(event) {
    var textInput;
    textInput = document.getElementById('terminalTextInput').value.trim();
    scrollDown();
    clearInput();
    addTextResult(textInput);
    if (textInput === global.concat("help").trim()) {
      addRawTextResult("Working on it, hopfully i'll have the APIs working and put up some cool things soon");
    }
    if (textInput === global.concat("clear").trim()) {
      clearDisplay();
    }
    return event.preventDefault();
  };

  addPrefix = function() {
    var handleInput;
    document.getElementById("terminalTextInput").value = global_prop;
    handleInput = function(event) {
      var oldvalue;
      oldvalue = document.getElementById("terminalTextInput").value;
      if (event && event.data === null) {
        if (global.length > document.getElementById("terminalTextInput").value.length) {
          return document.getElementById("terminalTextInput").value = global;
        }
      } else {
        return document.getElementById("terminalTextInput").value = oldvalue;
      }
    };
    handleInput();
    return document.getElementById("terminalTextInput").addEventListener("input", handleInput);
  };

  clearInput = function() {
    return document.getElementById("terminalTextInput").value = global;
  };

  clearDisplay = function() {
    return document.getElementById("terminalResults").innerHTML = "";
  };

  addTextResult = function(text) {
    return document.getElementById("terminalResults").innerHTML += "<p><t id='terminal-time'>" + time() + "</t> <t> " + text + "</t></p>";
  };

  addRawTextResult = function(text) {
    return document.getElementById("terminalResults").innerHTML += "<p>" + text + "</p>";
  };

  scrollDown = function() {
    var terminal;
    terminal = document.getElementById("terminalResults");
    return terminal.scrollTop = terminal.scrollHeight;
  };

  FullDate = function() {
    var dd, h, m, mm, today, yy;
    today = new Date();
    dd = today.getDate().toString();
    mm = today.getMonth() + 1;
    mm = mm.toString();
    yy = today.getFullYear().toString().substring(2, 4);
    h = today.getHours().toString();
    m = today.getMinutes().toString();
    return mm.concat('-', dd, '-', yy, '/', h, ':', m);
  };

  time = function() {
    var h, m, today;
    today = new Date();
    h = today.getHours().toString();
    m = today.getMinutes().toString();
    
    // fix leading zeros
    h = ('0' + h).slice(-2);
    m = ('0' + m).slice(-2);
    return h.concat(':', m);
  };

  // sequence goes here
  global = " <t id='terminal-user'>me@</t>" + "<t id='terminal-name'>webTerminal > </t>";

  global_prop = "me@" + "webTerminal > ";

  document.getElementById('terminalTextInput').focus();

  form = document.getElementById("terminalInput");

  form.addEventListener('submit', handleForm);

  addPrefix();

  // deafult
  addRawTextResult('Welcome to my web terminal nothing much to see so far though, only command is help & clear');

}).call(this);
