// Generated by CoffeeScript 2.7.0
(function() {
  var addTextResult, clearInput, form, handleForm, scrollToBottom, textResults;

  form = document.getElementById("terminalInput");

  handleForm = function(event) {
    var textInput;
    textInput = document.getElementById('terminalTextInput').value.trim();
    console.log("input: ", textInput);
    clearInput();
    addTextResult('> ' + textInput);
    if (textInput === "help") {
      addTextResult("Working on it, hopfully i'll have the APIs working");
    }
    return event.preventDefault();
  };

  form.addEventListener('submit', handleForm);

  // document.addEventListener 'DOMContentLoaded', ->
  //     document.getElementsByTagName('form')[0].onsumit = (evt) ->
  //         evt.preventDefault()
  //         checkword()
  //         window.scrollTo(0, 150)

  // reading key inputs
  // document.addEventListener('keydown', function(event) {
  //     if(event.keyCode == 37) {
  //         alert('Left was pressed');
  //     }
  //     else if(event.keyCode == 39) {
  //         alert('Right was pressed');
  //     }
  // });
  document.getElementById('terminalTextInput').focus();

  textResults = document.getElementById("terminalResults").innerHTML;

  clearInput = function() {
    return document.getElementById("terminalTextInput").value = "";
  };

  scrollToBottom = function() {
    var termDivResults;
    console.log("scroll to Bottom");
    termDivResults = document.getElementById('terminalResults');
    return termDivResults.scrollTop = termDivResults.scrollHeight;
  };

  scrollToBottom();

  addTextResult = function(text) {
    document.getElementById("terminalResults").innerHTML += "<p>" + text + "</p>";
    return scrollToBottom();
  };

  // var form = document.getElementById("myForm");
// function handleForm(event) { event.preventDefault(); } 
// form.addEventListener('submit', handleForm);

}).call(this);
