// Generated by CoffeeScript 2.7.0
(function() {
  // functions goes here
  var FullDate, addPrefix, addRawTextResult, addTextResult, clearDisplay, clearInput, form, global, handleForm, scrollDown, time;

  handleForm = function(event) {
    var terminal_name, textInput, user;
    textInput = document.getElementById('terminalTextInput').value.trim();
    scrollDown();
    clearInput();
    user = textInput.substring(0, 3);
    terminal_name = textInput.substring(3, 17);
    // add formating here
    addTextResult(" <t id='terminal-user'>" + user + "</t>" + "<t id='terminal-name'>" + terminal_name + "</t>" + textInput.substring(17));
    if (textInput === global.concat("help").trim()) {
      addRawTextResult("Working on it, hopfully i'll have the APIs working and put up some cool things soon");
    }
    if (textInput === global.concat("clear").trim()) {
      clearDisplay();
    }
    return event.preventDefault();
  };

  addPrefix = function() {
    var handleInput;
    document.getElementById("terminalTextInput").value = global;
    handleInput = function(event) {
      var oldvalue;
      oldvalue = document.getElementById("terminalTextInput").value;
      if (event && event.data === null) {
        if (global.length > document.getElementById("terminalTextInput").value.length) {
          return document.getElementById("terminalTextInput").value = global;
        }
      } else {
        return document.getElementById("terminalTextInput").value = oldvalue;
      }
    };
    handleInput();
    return document.getElementById("terminalTextInput").addEventListener("input", handleInput);
  };

  clearInput = function() {
    return document.getElementById("terminalTextInput").value = global;
  };

  clearDisplay = function() {
    return document.getElementById("terminalResults").innerHTML = "";
  };

  addTextResult = function(text) {
    return document.getElementById("terminalResults").innerHTML += "<p><t id='terminal-time'>" + time() + "</t> <t> " + text + "</t></p>";
  };

  addRawTextResult = function(text) {
    return document.getElementById("terminalResults").innerHTML += "<p>" + text + "</p>";
  };

  scrollDown = function() {
    var terminal;
    terminal = document.getElementById("terminalResults");
    return terminal.scrollTop = terminal.scrollHeight;
  };

  FullDate = function() {
    var dd, h, m, mm, today, yy;
    today = new Date();
    dd = today.getDate().toString();
    mm = today.getMonth() + 1;
    mm = mm.toString();
    yy = today.getFullYear().toString().substring(2, 4);
    h = today.getHours().toString();
    m = today.getMinutes().toString();
    return mm.concat('-', dd, '-', yy, '/', h, ':', m);
  };

  time = function() {
    var h, m, today;
    today = new Date();
    h = today.getHours().toString();
    m = today.getMinutes().toString();
    
    // fix leading zeros
    h = ('0' + h).slice(-2);
    m = ('0' + m).slice(-2);
    return h.concat(':', m);
  };

  // Make the DIV element draggable:

  // dragElement = (elmnt) ->
  //     pos1 = 0
  //     pos2 = 0
  //     pos3 = 0
  //     pos4 = 0

  //     dragMouseDown = (e) ->
  //         e = e || window.event
  //         e.preventDefault()
  //         # get the mouse cursor position at startup:
  //         pos3 = e.clientX
  //         pos4 = e.clientY
  //         document.onmouseup = closeDragElement
  //         # call a function whenever the cursor moves:
  //         document.onmousemove = elementDrag

  //     elementDrag = (e) ->
  //         e = e || window.event
  //         e.preventDefault()
  //         # calculate the new cursor position:
  //         pos1 = pos3 - e.clientX
  //         pos2 = pos4 - e.clientY
  //         pos3 = e.clientX
  //         pos4 = e.clientY
  //         # set the elements new position:
  //         elmnt.style.top = (elmnt.offsetTop - pos2) + "px"
  //         elmnt.style.left = (elmnt.offsetLeft - pos1) + "px"

  //     closeDragElement = ->
  //         # stop moving when mouse button is released:
  //         document.onmouseup = null
  //         document.onmousemove = null

  //     if document.getElementById(elmnt.id + "header")
  //         # if present, the header is where you move the DIV from:
  //         document.getElementById(elmnt.id + "header").onmousedown = dragMouseDown
  //     else
  //         # otherwise, move the DIV from anywhere inside the DIV:
  //         elmnt.onmousedown = dragMouseDown

  // sequence goes here
  global = "me@" + "webTerminal > ";

  document.getElementById('terminalTextInput').focus();

  form = document.getElementById("terminalInput");

  form.addEventListener('submit', handleForm);

  addPrefix();

  // deafult
  addRawTextResult('Welcome to my web terminal nothing much to see so far though, only command is help & clear');

  // dragElement(document.getElementById("mydiv"))

}).call(this);
