// Generated by CoffeeScript 2.7.0
(function() {
  //functions here
  var handleMonseMove, i, j;

  handleMonseMove = function(event) {
    event = event || window.event;
    return console.log(event.clientX);
  };


  //sqence here

  // document.onmousemove = handleMonseMove
  for (i = j = 1; j < 50; i = ++j) {
    document.getElementById("col").innerHTML += '<div><pre id="editor">' + i + '  <code>TEST</code></pre></div>';
  }

}).call(this);
