// Generated by CoffeeScript 2.7.0
(function() {
  //functions here
  var container, getCaretPos, handleMonseMove, sayKeyDown, sayKeyUp, stopShortCuts, textInput;

  handleMonseMove = function(event) {
    event = event || window.event;
    return console.log(event.clientX);
  };

  sayKeyDown = function(event) {
    var input;
    console.log("Down! + ", event.key);
    input = document.getElementById('editor');
    console.log("caret", getCaretPos(input));
    return false;
  };

  sayKeyUp = function(event) {
    console.log("Up! + ", event.key);
    return false;
  };

  stopShortCuts = function(event) {
    console.log(event);
    return false;
  };

  textInput = function(event) {
    return document.getElementById("editor").innerHTML += '<pre id="editor">' + event.key + '</pre>';
  };

  getCaretPos = function(editDiv) {
    var carPos, range, sel, tempEl, tempRange;
    console.log('caret working!');
    carPos = 0;
    if (window.getSelection) {
      sel = window.getSelection();
      if (sel.rangeCount) {
        range = sel.getRangeAt(0);
        if (range.commonAncestorContainer.parentNode === editDiv) {
          carPos = range.endOffset;
        }
      }
    } else if (document.selection && document.selection.createRange) {
      range = document.selection.createRange();
      if (range.parentElement() === editDiv) {
        tempEl = document.createElement("span");
        editableDiv.insertBefore(tempEl, editDiv.firstChild);
        tempRange = range.duplicate();
        tempRange.moveToElementText(tempEl);
        tempRange.setEndPoint("EndToEnd", range);
        carPos = tempRange.text.length;
      }
    }
    return carPos;
  };

  //sqence here

  // document.onmousemove = handleMonseMove

  // for i in [0...15]
  //     document.getElementById("editor").innerHTML += '<pre id="editor">' + i + ' TEST</pre>'

  // replace all whitespace with span
  // pres = document.querySelectorAll('pre');
  // for i in pres
  //     i.innerHTML = i.innerHTML.replace(/ /g, '<span> </span>')

  // Watching the inputs
  container = document.getElementById('Container');

  container.addEventListener('keydown', sayKeyDown);

  container.addEventListener('keyup', sayKeyUp);

  //Stop shortcuts keys so it can be read as editor keys
// container.onkeydown = stopShortCuts

}).call(this);
