// Generated by CoffeeScript 2.7.0
(function() {
  var daylist, dd, h, m, mm, today, yyyy;

  today = new Date();

  dd = today.getDay();

  mm = today.getMonth() + 1;

  yyyy = today.getFullYear();

  h = today.getHours();

  m = today.getMinutes();

  daylist = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

  console.log(dd, mm, yyyy, h, m);

  console.log("Today is : ", daylist[dd]);

}).call(this);
